### ISSUE TITLE
br is not selected over gzip

### ISSUE THREAD

**Issue by uhop** [tuananh/kompression#2]
That makes the package never even try `br`.

My example:

* Request headers:
  ```
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
  Accept-Encoding: gzip, deflate, br
  ```
* Response headers:
  ```
  Content-Encoding: gzip
  ```

What is the point? Or did I miss the use case?

**Comment by MuwuM** [comment]
This is the consequence of the impelementation of `ctx.acceptsEncodings` of Koa. (as discussed here https://github.com/koajs/send/issues/83). `ctx.acceptsEncodings` will take the first match with the highest [quality value](https://developer.mozilla.org/en-US/docs/Glossary/Quality_Values). 

If you want to prefer `br` over the rest you could add the following before the compress:

```
app.use((ctx,next)=>{
    if(ctx.acceptsEncodings('br')){
        ctx.request.header['accept-encoding']="br";
    }
    return next();
});
app.use(compress(/* ... */));
```

**Comment by uhop** [comment]
I am not sure that this is a good solution in general, but it works.
